import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir,hostname} from 'node:os';
import {randomUUID} from 'node:crypto';
import {runInNewContext} from 'node:vm';
import {syncCatalog} from '../catalog-sync.mjs';
import {readPointer,defaultPointerPath,repoRoot} from '../../storefront/products/snapshot-acceptance.mjs';
import {readFeedsOf} from './snapshot.mjs';
import {pinMedia} from './media.mjs';
import {publish} from './publish.mjs';
import {formatMessage} from './notify.mjs';
import {accept} from '../../storefront/catalog-import/import.mjs';
import {annotateLeadForms} from '../../storefront/client/lead-schema.js';
import {csvRecords} from '../../supabase/functions/_shared/product-rules.mjs';
import {renderProductPage} from '../../storefront/products/product-page.mjs';
const base=await readFeedsOf(readPointer().manifestPath), pointer=await fs.readFile(defaultPointerPath);
const manifest=JSON.parse(await fs.readFile(readPointer().mediaPath)), photo=manifest.assets.find(a=>a.rawURL.includes('/le-catalog-images/')&&a.contentType==='image/webp');
const quote=v=>'"'+String(v).replaceAll('"','""')+'"';
function feedsFor(url,active='TRUE'){const row={...csvRecords(base.feeds.trees).find(r=>r.photos.includes(photo.rawURL)),photos:url,active};const h=Object.keys(row);return {...base.feeds,trees:[h.map(quote).join(','),h.map(k=>quote(row[k])).join(',')].join('\n'),decor:base.feeds.decor.split(/\r?\n/)[0]};}
const inputs=feeds=>Object.fromEntries(['trees','decor','promos'].map(n=>[n,{...base.manifest.feeds[n],text:feeds[n]}]));
const deps={diskGuard:async()=>{},prepareBlog:async()=>({status:'unchanged'}),fetchInputs:async()=>inputs(base.feeds)};
async function isolated(fn){const dir=await fs.mkdtemp(join(tmpdir(),'le-review-'));try{await fs.writeFile(join(dir,'active.json'),pointer);await fn(dir,join(dir,'active.json'));}finally{await fs.rm(dir,{recursive:true,force:true});}}
test('1 dead PID/expired legacy lock recovers; live owner is a loud error',async()=>isolated(async(dir,p)=>{const lock=p+'.sync-lock';await fs.mkdir(lock);await fs.writeFile(join(lock,'owner.json'),JSON.stringify({pid:2147483647,hostname:hostname(),heartbeat:Date.now()-3600000}));const r=await syncCatalog({pointerPath:p},{...deps,pinMedia:async()=>({assets:manifest.assets,failures:[]})});assert.equal(r.status,'unchanged');await fs.mkdir(lock);await fs.writeFile(join(lock,'owner.json'),JSON.stringify({pid:process.pid,hostname:hostname(),heartbeat:Date.now()}));await assert.rejects(syncCatalog({pointerPath:p},deps),/lock|занят/i);}));
test('2 unchanged ETag does not transfer image body; replacement at same URL does',async()=>{const dir=await fs.mkdtemp(join(tmpdir(),'le-review-media-'));try{const prior={...photo,etag:'"v1"'};const file=join(dir,'media.json');await fs.writeFile(file,JSON.stringify({assets:[prior]}));let full=0;const m=await pinMedia(feedsFor(photo.rawURL),{extraManifests:[file],fetchImpl:async(url,opts)=>{if(opts.headers['If-None-Match']==='"v1"')return new Response(null,{status:304});full++;return new Response(await fs.readFile(join(repoRoot,photo.localPath)),{headers:{'content-type':'image/webp'}});}});assert.equal(m.failures.length,0);assert.equal(full,0);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('3 releases deduplicate unchanged bytes and prune only after switch',async()=>isolated(async dir=>{const dist=join(dir,'dist'),target=join(dir,'current');await fs.mkdir(dist);await fs.writeFile(join(dist,'photo'),'same');await fs.writeFile(join(dist,'index'),'0');const first=await publish(dist,{method:'dir',env:{LE_DEPLOY_DIR:target,LE_DEPLOY_KEEP_RELEASES:'2'}});await fs.writeFile(join(dist,'index'),'1');const second=await publish(dist,{method:'dir',env:{LE_DEPLOY_DIR:target,LE_DEPLOY_KEEP_RELEASES:'2'}});assert.equal((await fs.stat(join(first.release,'photo'))).ino,(await fs.stat(join(second.release,'photo'))).ino);await fs.writeFile(join(dist,'index'),'2');await publish(dist,{method:'dir',env:{LE_DEPLOY_DIR:target,LE_DEPLOY_KEEP_RELEASES:'2'}});assert.equal((await fs.readdir(target+'.releases')).length,2);assert.equal(await fs.readFile(join(target,'index'),'utf8'),'2');}));
// Bundle the real forms.js with its real imports (request-errors.js, config.js, lead-schema.js), then run it in a bare
// context without AbortSignal.timeout / crypto.randomUUID (iOS<16) and without a real network: nothing is stubbed in the client.
async function bundleForms(sourcePath='storefront/client/forms.js'){const {build}=await import('esbuild');const out=await build({entryPoints:[join(repoRoot,sourcePath)],bundle:true,format:'iife',globalName:'__forms',write:false,logLevel:'silent'});const code=out.outputFiles[0].text;assert.ok(code.includes('RequestFailure')&&code.includes('function postJson'),'real request-errors.js must be bundled, not stubbed');assert.doesNotMatch(code,/AbortSignal\.timeout/,'lead client must not use AbortSignal.timeout (iOS<16)');return code;}
async function formsAPI(fetchOverride){const code=await bundleForms();const ctx={AbortController,setTimeout,clearTimeout,crypto:{getRandomValues:b=>{b.fill(42);return b}},__LE_STOREFRONT_CONFIG__:{mode:'preview',lead:'/lead'},fetch:async()=>new Response('<html>bad gateway</html>',{status:502}),Response};if(fetchOverride)ctx.fetch=fetchOverride;runInNewContext(code+';globalThis.api={requestLead:__forms.requestLead,leadId:__forms.leadId};',ctx);return ctx.api;}
test('4 browser without AbortSignal.timeout/randomUUID sends and releases timer',async()=>{const api=await formsAPI();assert.match(api.leadId(),/^[a-f0-9-]{36}$/);await assert.rejects(api.requestLead({}),/Сервис.*временно/i);});
test('5 crash before candidate commit never exposes incomplete target',async()=>{const target=join(repoRoot,'storefront/catalog-import/candidates','review-'+randomUUID());try{await assert.rejects(accept(inputs(base.feeds),{output:target,beforeCommit:async()=>{await assert.rejects(fs.stat(target),{code:'ENOENT'});throw Error('simulated kill');}}),/simulated kill/);await assert.rejects(fs.stat(target),{code:'ENOENT'});}finally{await fs.rm(target,{recursive:true,force:true});}});
test('6 inactive deleted media skipped; active transient 503 retries then uses verified cache',async()=>{const url=photo.rawURL.replace(/[^/]+$/,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.webp');const inactive=await pinMedia(feedsFor(url,'FALSE'),{fetchImpl:async()=>new Response(null,{status:404})});assert.equal(inactive.failures.length,0);let calls=0;const active=await pinMedia(feedsFor(photo.rawURL),{retryDelay:0,fetchImpl:async()=>{calls++;return new Response(null,{status:503});}});assert.equal(active.failures.length,0);assert.equal(calls,3);assert.equal(active.assets[0].sha256,photo.sha256);});
test('7 persistent identical block sends once; transient changing feed is quiet retry',async()=>isolated(async(dir,p)=>{let sends=0;const blocked={...base.feeds,trees:base.feeds.trees.split(/\r?\n/)[0]};const d={...deps,fetchInputs:async()=>inputs(blocked),notify:async()=>{sends++;return {sent:true};}};for(let i=0;i<2;i++)assert.equal((await syncCatalog({pointerPath:p,dryRun:false,method:'dir'},d)).status,'blocked');assert.equal(sends,1);const r=await syncCatalog({pointerPath:p,dryRun:false,method:'dir'},{...d,fetchInputs:async()=>{throw Object.assign(Error('changing'),{code:'CATALOG_CHANGING'});}});assert.equal(r.status,'retry');assert.equal(sends,1);}));
test('8 long ampersand notice never splits HTML entities/tags',()=>{const msg=formatMessage({title:'&'.repeat(2000),lines:['&'.repeat(3000)]});assert.ok(msg.length<=3900);assert.ok(msg.includes('</b>'));assert.ok(!/&(?:a(?:m(?:p)?)?)?$/.test(msg));});
test('9 dollar replacement tokens survive product JSON and metadata',async()=>{const title="Sale $' $` $&",product={id:'x',kind:'decor',title,variants:[],selectedVariant:null};const template=await fs.readFile('storefront/public/catalog-tree/korzina-pod-yelku.html','utf8');const html=renderProductPage(template,product,{},title);const json=/<script type="application\/json" data-storefront-page-product>([^]*?)<\/script>/.exec(html)[1];assert.equal(JSON.parse(json).title,title);const s=await fs.readFile('storefront/generate-products.mjs','utf8');const body=s.slice(s.indexOf('function metadata('),s.indexOf('for (const route of routes)'));const ctx={escape:v=>String(v).replaceAll('&','&amp;').replaceAll('\"','&quot;').replaceAll('<','&lt;').replaceAll("'",'&#39;')};runInNewContext(body+';globalThis.meta=metadata;',ctx);const metadata=ctx.meta('<head><title>Old</title><meta name=\"description\" content=\"old\"></head>',{path:'/x'},product,title);assert.ok(metadata.includes('<title>'+ctx.escape(title)+'</title>'));assert.ok(metadata.includes('content=\"'+ctx.escape(title)+'\"'));assert.equal(JSON.parse(/<script type=\"application\/ld\+json\">([^]*?)<\/script>/.exec(metadata)[1]).name,title);});
test('10 no JS contact forms cannot send personal fields in GET or submit unmounted',async()=>{const raw=await fs.readFile('storefront/components/question-form-section.html','utf8');const html=annotateLeadForms(raw);assert.match(html,/<form[^>]*method="post"/);assert.match(html,/<(?:button|input)[^>]*data-lead-enable[^>]*disabled/);const index=await fs.readFile('storefront/client/index.js','utf8');assert.ok(index.indexOf('  initForms();')<index.indexOf('  initProducts();'));});
test('11 HTML gateway and network errors produce human text, never parser/transport detail',async()=>{const api=await formsAPI();await assert.rejects(api.requestLead({}),e=>/временно/.test(e.message)&&!e.message.includes('Unexpected'));});

import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {acquireLock} from './lock.mjs';
import {throttledNotify} from './notify.mjs';
import {createHash} from 'node:crypto';
import {snapshotsRoot} from '../../storefront/products/snapshot-acceptance.mjs';
const digest=s=>createHash('sha256').update(s).digest('hex');
const pause=ms=>new Promise(r=>setTimeout(r,ms));
test('1 process SIGKILL recovery and SIGTERM work/lock cleanup; TTL foreign/legacy ownership',async()=>isolated(async(dir,p)=>{
 const source=`import {syncCatalog} from ${JSON.stringify(new URL('../catalog-sync.mjs',import.meta.url).href)};import {readPointer} from ${JSON.stringify(new URL('../../storefront/products/snapshot-acceptance.mjs',import.meta.url).href)};import {readFeedsOf} from ${JSON.stringify(new URL('./snapshot.mjs',import.meta.url).href)};import {pinMedia} from ${JSON.stringify(new URL('./media.mjs',import.meta.url).href)};const base=await readFeedsOf(readPointer().manifestPath);await syncCatalog({pointerPath:process.argv[1]},{diskGuard:async()=>{},fetchInputs:async()=>Object.fromEntries(['trees','decor','promos'].map(n=>[n,{...base.manifest.feeds[n],text:base.feeds[n]}])),pinMedia:feeds=>pinMedia(feeds,{refreshRemote:false,persistCache:false}),prepareBlog:async()=>new Promise(()=>{setInterval(()=>{},1000);console.log('ready')})});`;

 for(const signal of ['SIGKILL','SIGTERM']){const child=spawn(process.execPath,['--input-type=module','-e',source,p],{stdio:['ignore','pipe','pipe']});const done=once(child,'exit');await new Promise((ok,fail)=>{child.stdout.once('data',ok);child.once('error',fail);child.once('exit',()=>fail(Error('early exit')));});const owner=JSON.parse(await fs.readFile(join(p+'.sync-lock','owner.json')));assert.ok(owner.work);await fs.stat(owner.work);child.kill(signal);await done;
 if(signal==='SIGKILL'){const lease=await acquireLock(p+'.sync-lock');await lease.release();}else await assert.rejects(fs.stat(p+'.sync-lock'),{code:'ENOENT'});
 await assert.rejects(fs.stat(owner.work),{code:'ENOENT'});
 }
 const lock=join(dir,'foreign');await fs.mkdir(lock);await fs.writeFile(join(lock,'owner.json'),JSON.stringify({hostname:'other-host',pid:1,heartbeat:Date.now()-10000}));const lease=await acquireLock(lock,{ttl:100});await lease.release();await fs.mkdir(lock);await fs.utimes(lock,new Date(0),new Date(0));const legacy=await acquireLock(lock,{ttl:100});await legacy.release();
}));
test('1 heartbeat and contention do not steal a live lease',async()=>isolated(async dir=>{const p=join(dir,'lock');const lease=await acquireLock(p,{heartbeatMs:5});const a=JSON.parse(await fs.readFile(join(p,'owner.json')));await pause(20);const b=JSON.parse(await fs.readFile(join(p,'owner.json')));assert.ok(b.heartbeat>a.heartbeat);const results=await Promise.allSettled(Array.from({length:5},()=>acquireLock(p)));assert.ok(results.every(r=>r.status==='rejected'&&r.reason.code==='SYNC_BUSY'));await lease.release();}));
test('2 same URL replacement changes sha; corrupted local cache cannot mask deletion',async()=>{const b=manifest.assets.find(a=>a.contentType==='image/webp'&&a.sha256!==photo.sha256);const bytes=await fs.readFile(join(repoRoot,b.localPath));const m=await pinMedia(feedsFor(photo.rawURL),{fetchImpl:async()=>new Response(bytes,{headers:{'content-type':'image/webp',etag:'"changed"'}})});assert.equal(m.assets[0].sha256,b.sha256);assert.equal(m.summary.downloaded,1);const missing=await pinMedia(feedsFor(photo.rawURL),{fetchImpl:async()=>new Response(null,{status:404})});assert.equal(missing.failures.length,1);});
test('3 SSH publication plan has link-dest and cleanup after atomic switch; failed upload never switches',async()=>{const env={LE_DEPLOY_RSYNC_TARGET:'fixture@host:/srv/site',LE_DEPLOY_KEEP_RELEASES:'5'};const plan=await publish('/fixture',{method:'rsync',env,planOnly:true});assert.ok(plan.commands[1][1].includes('--link-dest=/srv/site'));assert.match(plan.commands[2][1].at(-1),/mv -Tf/);assert.match(plan.commands[3][1].at(-1),/tail -n \+6/);const calls=[];await assert.rejects(publish('/fixture',{method:'rsync',env,runImpl:async(cmd,args)=>{calls.push([cmd,args]);if(cmd==='rsync')throw Error('upload failure');}}),/upload failure/);assert.ok(!calls.some(([,a])=>a.at(-1).includes('mv -Tf')));assert.match(calls.at(-1)[1].at(-1),/rm -rf/);});
test('5 old incomplete deterministic candidate is quarantined and same data builds again',async()=>isolated(async(dir,p)=>{
 const rows=csvRecords(base.feeds.trees),headers=Object.keys(rows[0]);rows.find(r=>r.id==='13'&&r.height_cm==='150').price='23001';const feeds={...base.feeds,trees:[headers.map(quote).join(','),...rows.map(r=>headers.map(k=>quote(r[k])).join(','))].join('\n')};const fh=digest(['trees','decor','promos'].map(n=>digest(feeds[n])).join('\n'));
 const mh=digest(JSON.stringify(manifest.assets.map(a=>[a.rawURL,a.sha256]).sort((a,b)=>a[0].localeCompare(b[0]))));
 const bh=digest(['trees','decor','promos'].map(n=>base.manifest.feeds[n].sha256).join('\n'));const id='auto-'+digest(fh+mh+bh).slice(0,32),candidate=join(repoRoot,'storefront/catalog-import/candidates',id);let quarantine;
 try{await fs.mkdir(candidate);await fs.writeFile(join(candidate,'trees.csv'),'partial');const r=await syncCatalog({pointerPath:p},{...deps,fetchInputs:async()=>inputs(feeds),pinMedia:async()=>({assets:manifest.assets,references:manifest.references,summary:manifest.summary,failures:[]}),build:async({output})=>{await fs.mkdir(output);await fs.writeFile(join(output,'product-routes.json'),'[]');}});assert.equal(r.status,'dry-run');quarantine=(await fs.readdir(join(candidate,'..'))).find(n=>n.startsWith(id+'.incomplete-'));assert.ok(quarantine);assert.equal(await fs.readFile(join(candidate,'..',quarantine,'trees.csv'),'utf8'),'partial');}
 finally{await fs.rm(candidate,{recursive:true,force:true});await fs.rm(join(snapshotsRoot,id),{recursive:true,force:true});if(quarantine)await fs.rm(join(candidate,'..',quarantine),{recursive:true,force:true});}
}));
test('7 throttle expiry, distinct incidents and failed delivery retry',async()=>isolated(async dir=>{let calls=0;const opts={statePath:join(dir,'notice.json'),now:1000,interval:100,send:async()=>{calls++;return {sent:true};}};await throttledNotify('a',opts);await throttledNotify('a',opts);await throttledNotify('b',opts);await throttledNotify('a',{...opts,now:1101});assert.equal(calls,3);await throttledNotify('fail',{...opts,send:async()=>({sent:false})});assert.equal((await throttledNotify('fail',opts)).sent,true);}));

async function formHarness(response, sourcePath=process.env.LE_REVIEW_FORMS_SOURCE||'storefront/client/forms.js', legacy=true) {
 const source=await bundleForms(sourcePath);
 const notices=[],posts=[],handlers={};const button={textContent:'Отправить',disabled:true,querySelector:()=>null,setAttribute(){}};
 const element=()=>({style:{},dataset:{},setAttribute(){},value:'',textContent:''});
 const form={id:'fixture',dataset:{leadType:'question'},method:'post',action:'http://local/',matches:()=>false,querySelector:()=>null,querySelectorAll:s=>s.includes('submit')||s==='[data-lead-enable]'?[button]:[],append:e=>notices.push(e),addEventListener:(n,fn)=>handlers[n]=fn,reset(){this.resetCalled=true;}};
 let timers=0;const ctx={document:{createElement:element},location:{href:'http://local/',origin:'http://local',pathname:'/'},__LE_STOREFRONT_CONFIG__:{mode:'preview',lead:'/lead'},crypto:{getRandomValues:b=>{b.fill(42);return b;}},AbortController,setTimeout:(fn,ms)=>{timers++;return setTimeout(fn,ms)},clearTimeout:t=>{timers--;clearTimeout(t)},fetch:async(url,opts)=>{posts.push(JSON.parse(opts.body));return response(opts);}};
 if(!legacy){ctx.crypto.randomUUID=()=> '11111111-1111-4111-8111-111111111111';ctx.AbortSignal=AbortSignal;}
 runInNewContext(source+';globalThis.mount=__forms.initForms;',ctx);ctx.mount({querySelectorAll:()=>[form]});
 return {form,button,posts,notices,timers:()=>timers,submit:()=>handlers.submit({preventDefault(){},stopImmediatePropagation(){}})};
}
test('4 actual form submits without randomUUID/AbortSignal; no leaked timer or stuck button',async()=>{const h=await formHarness(async()=>Response.json({ok:true}));await h.submit();assert.equal(h.posts.length,1);assert.match(h.posts[0].id,/^[a-f0-9-]{36}$/);assert.equal(h.form.resetCalled,true);assert.equal(h.button.disabled,false);assert.equal(h.timers(),0);});
test('11 actual form gateway/network errors stay human and preserve request ID',async()=>{let count=0;const h=await formHarness(async()=>{if(++count===1)return new Response('<html>bad gateway</html>',{status:502});throw Error('Failed to fetch private detail');},undefined,false);await h.submit();const first=h.posts[0].id;assert.match(h.notices.at(-1).textContent,/временно/);await h.submit();assert.equal(h.posts[1].id,first);assert.match(h.notices.at(-1).textContent,/Сервис временно недоступен.*свяжитесь с нами/);assert.ok(!h.notices.at(-1).textContent.includes('private'));assert.equal(h.button.disabled,false);assert.equal(h.timers(),0);});

test('4 timeout fallback aborts a hanging request and releases timer',async()=>{const api=await formsAPI(async(url,opts)=>new Promise((ok,fail)=>opts.signal.addEventListener('abort',()=>fail(Object.assign(Error('aborted'),{name:'AbortError'})),{once:true})));await assert.rejects(api.requestLead({},{timeoutMs:2}),/номер заявки сохранён/);});

test('2 unchanged runs retain validators durably, downloading once across repeated runs',async()=>isolated(async dir=>{
 const cachePath=join(dir,'cache.json'),url=photo.rawURL.replace(/[^/]+$/,'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.webp');let bodies=0;
 const fetchImpl=async(u,opts)=>{if(opts.headers['If-None-Match']==='"cached"')return new Response(null,{status:304});bodies++;return new Response(await fs.readFile(join(repoRoot,photo.localPath)),{headers:{'content-type':'image/webp',etag:'"cached"'}});};
 const opts={cachePath,persistCache:true,fetchImpl};const first=await pinMedia(feedsFor(url),opts);const second=await pinMedia(feedsFor(url),opts);assert.equal(first.failures.length,0);assert.equal(second.failures.length,0);assert.equal(bodies,1);assert.equal(second.summary.downloadBytes,0);assert.equal(JSON.parse(await fs.readFile(cachePath)).assets.find(a=>a.rawURL===url).etag,'"cached"');
}));
test('6 snapshot validates with unpinned inactive reference while active media remains mandatory',async()=>isolated(async(dir,p)=>{
 const rows=csvRecords(base.feeds.trees),headers=Object.keys(rows[0]),row=rows.find(r=>r.active==='FALSE');assert.ok(row);row.photos=photo.rawURL.replace(/[^/]+$/,'cccccccccccccccccccccccccccccccc.webp');
 const feeds={...base.feeds,trees:[headers.map(quote).join(','),...rows.map(r=>headers.map(k=>quote(r[k])).join(','))].join('\n')};let id;
 try{const m=await pinMedia(feeds,{refreshRemote:false,fetchImpl:async()=>{throw Error('unexpected network')}});assert.equal(m.failures.length,0);assert.equal(m.references.find(r=>r.url===row.photos).mediaStatus,'skipped-inactive');const result=await syncCatalog({pointerPath:p},{...deps,fetchInputs:async()=>inputs(feeds),pinMedia:async()=>m,build:async({output,pointerPath})=>{id=readPointer(pointerPath).id;await fs.mkdir(output);await fs.writeFile(join(output,'product-routes.json'),'[]');}});assert.equal(result.status,'dry-run');}
 finally{if(id){await fs.rm(join(snapshotsRoot,id),{recursive:true,force:true});await fs.rm(join(repoRoot,'storefront/catalog-import/candidates',id),{recursive:true,force:true});}}
}));
